//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhong_KhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangNhap_QL
    {
        public DangNhap_QL()
        {
            this.KhachSans = new HashSet<KhachSan>();
        }
    
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string SDT_QL { get; set; }
        public string Mail_QL { get; set; }
    
        public virtual ICollection<KhachSan> KhachSans { get; set; }
    }
}
