//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatPhong_KhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangNhap_KH
    {
        public DangNhap_KH()
        {
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public string TenDN { get; set; }
        public string MK { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string CMND { get; set; }
        public string TenHienThi { get; set; }
    
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
    }
}
